FROM flowm2m/dotnet-mono-base

COPY . /app

WORKDIR /app

RUN mv /app/DTLS.Net/src/DTLS.Net /app/src
RUN mv /app/DTLS.Net/test/TestClient /app/test
RUN mv /app/DTLS.Net/test/TestServer /app/test

RUN dotnet restore && \
  dotnet build --configuration=Debug src/* && \
  dotnet build --configuration=Debug test/*




